import { Timestamp } from "firebase/firestore";
import type { Template } from "./firestore-types";

const now = () => Timestamp.now();

// Curated commercial / tech / product Unsplash images (3:4 friendly crops).
const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=600&h=800&fit=crop&q=80`;

export const TEMPLATES: Template[] = [
  // ─── Reels (4) ─────────────────────────────────────────────────────────────
  {
    id: "reels-yaz-indirimi",
    title: "Yaz İndirimi Reels",
    description: "Sıcak yaz kampanyaları için yüksek dönüşümlü 15 saniyelik dikey reklam.",
    category: "reels",
    serviceId: "reels",
    previewUrl: img("1522199755839-a2bacb67c546"),
    previewType: "image",
    tags: ["yaz", "indirim", "kampanya", "9:16"],
    popularity: 96,
    isNew: true,
    createdAt: now(),
  },
  {
    id: "reels-urun-lansmani-30",
    title: "Ürün Lansmanı 30sn",
    description: "Yeni ürününüzü patlatan dinamik 30 saniyelik lansman reels şablonu.",
    category: "reels",
    serviceId: "reels",
    previewUrl: img("1556761175-5973dc0f32e7"),
    previewType: "image",
    tags: ["lansman", "ürün", "viral"],
    popularity: 88,
    createdAt: now(),
  },
  {
    id: "reels-trend-dans",
    title: "Trend Dans Reels",
    description: "Viral trendlere uyum sağlayan, sıralı kesim hızlı dans formatı.",
    category: "reels",
    serviceId: "reels",
    previewUrl: img("1611162617213-7d7a39e9b1d7"),
    previewType: "image",
    tags: ["trend", "dans", "viral", "tiktok"],
    popularity: 74,
    createdAt: now(),
  },
  {
    id: "reels-musteri-yorumu",
    title: "Müşteri Yorumu Reels Pro",
    description: "Gerçek müşteri yorumlarını sinematik anlatımla sunan PRO şablon.",
    category: "reels",
    serviceId: "reels",
    previewUrl: img("1573497019418-b400bb3ab074"),
    previewType: "image",
    tags: ["yorum", "ugc", "güven"],
    popularity: 81,
    isPro: true,
    creditCost: 50,
    createdAt: now(),
  },

  // ─── Product Photo (4) ─────────────────────────────────────────────────────
  {
    id: "photo-beyaz-zemin",
    title: "Ürün Fotoğrafı Beyaz Zemin",
    description: "E-ticaret için pazaryeri uyumlu, temiz beyaz zeminli stüdyo görseli.",
    category: "product-photo",
    serviceId: "product-photo",
    previewUrl: img("1505740420928-5e560c06d30e"),
    previewType: "image",
    tags: ["beyaz zemin", "trendyol", "amazon"],
    popularity: 92,
    createdAt: now(),
  },
  {
    id: "photo-lifestyle-acik",
    title: "Lifestyle Çekim Açık Tonlar",
    description: "Doğal ışık ve pastel tonlarla lifestyle ürün fotoğrafı.",
    category: "product-photo",
    serviceId: "product-photo",
    previewUrl: img("1483985988355-763728e1935b"),
    previewType: "image",
    tags: ["lifestyle", "pastel", "doğal ışık"],
    popularity: 79,
    isNew: true,
    createdAt: now(),
  },
  {
    id: "photo-lux-mucevher",
    title: "Lüks Mücevher Stüdyo Pro",
    description: "Mücevher ve premium ürünler için karanlık stüdyo, makro detay.",
    category: "product-photo",
    serviceId: "product-photo",
    previewUrl: img("1515562141207-7a88fb7ce338"),
    previewType: "image",
    tags: ["lüks", "mücevher", "premium"],
    popularity: 68,
    isPro: true,
    creditCost: 80,
    createdAt: now(),
  },
  {
    id: "photo-360-katalog",
    title: "360° Katalog Görseli",
    description: "Dönen ürün gösterimi için çok açılı katalog şablonu.",
    category: "product-photo",
    serviceId: "product-photo",
    previewUrl: img("1542291026-7eec264c27ff"),
    previewType: "image",
    tags: ["360", "katalog", "çoklu açı"],
    popularity: 71,
    createdAt: now(),
  },

  // ─── Campaign (4) ──────────────────────────────────────────────────────────
  {
    id: "campaign-black-friday",
    title: "Black Friday Patlaması",
    description: "Yüksek tempolu, neon vurgu efektli kampanya filmi şablonu.",
    category: "campaign",
    serviceId: "campaign",
    previewUrl: img("1607082348824-0a96f2a4b9da"),
    previewType: "image",
    tags: ["black friday", "indirim", "neon"],
    popularity: 95,
    isNew: true,
    createdAt: now(),
  },
  {
    id: "campaign-yilbasi",
    title: "Yılbaşı Hediye Kampanyası",
    description: "Sıcak ışıklar ve kar efektleriyle yılbaşı kampanya videosu.",
    category: "campaign",
    serviceId: "campaign",
    previewUrl: img("1543589077-47d81606c1bf"),
    previewType: "image",
    tags: ["yılbaşı", "hediye", "kış"],
    popularity: 70,
    createdAt: now(),
  },
  {
    id: "campaign-flash-sale",
    title: "Flash Sale 24 Saat",
    description: "Geri sayım hissi yaratan, aciliyet odaklı 15 saniyelik kampanya.",
    category: "campaign",
    serviceId: "campaign",
    previewUrl: img("1611926653458-09294b3142bf"),
    previewType: "image",
    tags: ["flash", "geri sayım", "aciliyet"],
    popularity: 83,
    createdAt: now(),
  },
  {
    id: "campaign-marka-hikayesi-pro",
    title: "Marka Hikayesi Pro",
    description: "Sinematik 60 saniyelik marka hikayesi anlatım filmi.",
    category: "campaign",
    serviceId: "campaign",
    previewUrl: img("1492724441997-5dc865305da7"),
    previewType: "image",
    tags: ["marka", "hikaye", "sinematik"],
    popularity: 64,
    isPro: true,
    creditCost: 120,
    createdAt: now(),
  },

  // ─── Corporate (4) ─────────────────────────────────────────────────────────
  {
    id: "corp-tanitim-pro",
    title: "Kurumsal Tanıtım Pro",
    description: "Modern ofis görselleri ve veri animasyonlu kurumsal tanıtım.",
    category: "corporate",
    serviceId: "corporate",
    previewUrl: img("1497366216548-37526070297c"),
    previewType: "image",
    tags: ["kurumsal", "tanıtım", "b2b"],
    popularity: 90,
    isPro: true,
    creditCost: 150,
    createdAt: now(),
  },
  {
    id: "corp-ekip-tanitim",
    title: "Ekip Tanıtım Filmi",
    description: "Şirket çalışanlarını tanıtan, sıcak ve profesyonel format.",
    category: "corporate",
    serviceId: "corporate",
    previewUrl: img("1522071820081-009f0129c71c"),
    previewType: "image",
    tags: ["ekip", "kültür", "ik"],
    popularity: 67,
    createdAt: now(),
  },
  {
    id: "corp-yatirimci",
    title: "Yatırımcı Sunumu Şablonu",
    description: "Veri odaklı, grafik animasyonlu yatırımcı tanıtım filmi.",
    category: "corporate",
    serviceId: "corporate",
    previewUrl: img("1454165804606-c3d57bc86b40"),
    previewType: "image",
    tags: ["yatırımcı", "pitch", "data"],
    popularity: 58,
    isNew: true,
    createdAt: now(),
  },
  {
    id: "corp-fuar-loop",
    title: "Fuar Stand Loop Video",
    description: "Etkinlik ve fuar standları için 30 saniyelik kesintisiz loop.",
    category: "corporate",
    serviceId: "corporate",
    previewUrl: img("1540575467063-178a50c2df87"),
    previewType: "image",
    tags: ["fuar", "etkinlik", "loop"],
    popularity: 52,
    createdAt: now(),
  },

  // ─── Social Media (4) ──────────────────────────────────────────────────────
  {
    id: "social-yaz-paketi",
    title: "Sosyal Medya Yaz Paketi",
    description: "12 post + 6 reels içeren komple yaz sezonu içerik paketi.",
    category: "social",
    serviceId: "social-media",
    previewUrl: img("1611605698335-8b1569810432"),
    previewType: "image",
    tags: ["yaz", "paket", "12 post"],
    popularity: 87,
    createdAt: now(),
  },
  {
    id: "social-influencer-strateji",
    title: "Influencer Takip Stratejisi",
    description: "Influencer iş birlikleri için içerik takvimi ve şablon paketi.",
    category: "social",
    serviceId: "social-media",
    previewUrl: img("1581291518857-4e27b48ff24e"),
    previewType: "image",
    tags: ["influencer", "strateji", "takvim"],
    popularity: 73,
    isPro: true,
    creditCost: 90,
    createdAt: now(),
  },
  {
    id: "social-haftalik-akis",
    title: "Haftalık Akış Şablonu",
    description: "7 gün için hazır görsel şablon ve caption önerileri.",
    category: "social",
    serviceId: "social-media",
    previewUrl: img("1611162616305-c69b3fa7fbe0"),
    previewType: "image",
    tags: ["haftalık", "caption", "instagram"],
    popularity: 80,
    isNew: true,
    createdAt: now(),
  },
  {
    id: "social-linkedin-pro",
    title: "LinkedIn B2B İçerik Pro",
    description: "Profesyonel ton, veri görselleri ve thought leadership formatı.",
    category: "social",
    serviceId: "social-media",
    previewUrl: img("1556761175-b413da4baf72"),
    previewType: "image",
    tags: ["linkedin", "b2b", "thought leadership"],
    popularity: 62,
    isPro: true,
    creditCost: 70,
    createdAt: now(),
  },

  // ─── Avatar (4) ────────────────────────────────────────────────────────────
  {
    id: "avatar-marka-sozcusu",
    title: "Avatar Marka Sözcüsü",
    description: "Markanız için 7/24 konuşan dijital sözcü avatar şablonu.",
    category: "avatar",
    serviceId: "avatar",
    previewUrl: img("1531746020798-e6953c6e8e04"),
    previewType: "image",
    tags: ["sözcü", "avatar", "dijital"],
    popularity: 91,
    isPro: true,
    creditCost: 200,
    createdAt: now(),
  },
  {
    id: "avatar-kapi-yuzu",
    title: "Kapı Yüzü Avatar Tanıtım",
    description: "Mağaza ve etkinlik girişi için karşılayıcı avatar formatı.",
    category: "avatar",
    serviceId: "avatar",
    previewUrl: img("1573496359142-b8d87734a5a2"),
    previewType: "image",
    tags: ["karşılama", "perakende", "avatar"],
    popularity: 56,
    createdAt: now(),
  },
  {
    id: "avatar-egitim",
    title: "Eğitim Sunucu Avatarı",
    description: "Online eğitim ve kurs içerikleri için sunucu avatar şablonu.",
    category: "avatar",
    serviceId: "avatar",
    previewUrl: img("1524178232363-1fb2b075b655"),
    previewType: "image",
    tags: ["eğitim", "kurs", "anlatıcı"],
    popularity: 69,
    isNew: true,
    createdAt: now(),
  },
  {
    id: "avatar-haber-spikeri",
    title: "Haber Spikeri Avatar Pro",
    description: "Kurumsal duyuru ve haber içerikleri için profesyonel spiker avatar.",
    category: "avatar",
    serviceId: "avatar",
    previewUrl: img("1494790108377-be9c29b29330"),
    previewType: "image",
    tags: ["spiker", "haber", "duyuru"],
    popularity: 77,
    isPro: true,
    creditCost: 180,
    createdAt: now(),
  },
];

export const TEMPLATE_CATEGORIES: {
  id: "all" | Template["category"];
  label: string;
}[] = [
  { id: "all", label: "Tümü" },
  { id: "reels", label: "Reels" },
  { id: "product-photo", label: "Ürün Fotoğrafı" },
  { id: "campaign", label: "Kampanya" },
  { id: "corporate", label: "Kurumsal" },
  { id: "social", label: "Sosyal Medya" },
  { id: "avatar", label: "Avatar" },
];

export const getFeaturedTemplates = (limit = 8): Template[] =>
  [...TEMPLATES].sort((a, b) => b.popularity - a.popularity).slice(0, limit);
